package(default_visibility = ["//visibility:private"])

alias(
    name = "app",
    actual = "//apps/macos:app",
)

test_suite(
    name = "tests",
    tests = [
        "//apps/macos:test",
        "//packages/core:test",
        "//packages/providers:test",
        "//tools/cognitive-complexity:test",
    ],
)
