package(default_visibility = ["//visibility:private"])

exports_files(
    ["LICENSE"],
    visibility = ["//apps/macos:__pkg__"],
)

alias(
    name = "app",
    actual = "//apps/macos:app",
)

test_suite(
    name = "tests",
    tests = [
        "//apps/macos:test",
        "//packages/core:test",
        "//packages/providers:test",
        "//tools/cognitive-complexity:test",
        "//tools/release:test",
    ],
)
